version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: Ad123
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: abbabe
      MYSQL_PASSWORD: Abbabe_1
    networks:
      - mysql_net
   # volumes:
   #   -myvol:/var/lib/mysql

  myapp:
    image: bookstore-api:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - mysql_net


networks:
  mysql_net:

#volumes:
  # myvol:{}

  